name: Go disgolink

on: [ push ]

jobs:
    gobuild:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3

            -   name: Set up Go
                uses: actions/setup-go@v3
                with:
                    go-version: 1.18

            -   name: go build
                run: go build -v ./disgolink/...

    govet:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3

            -   name: Set up Go
                uses: actions/setup-go@v3
                with:
                    go-version: 1.18

            -   name: go vet
                run: go vet -v ./disgolink/...

    gotest:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3

            -   name: Set up Go
                uses: actions/setup-go@v3
                with:
                    go-version: 1.18

            -   name: go test
                env:
                    token: ${{ secrets.TOKEN }}
                run: go test -v ./disgolink/...

gostaticcheck:
    runs-on: ubuntu-latest
    steps:
        -   uses: actions/checkout@v3

        -   name: Set up Go
            uses: actions/setup-go@v3
            with:
                go-version: 1.18

        -   name: go staticcheck
            uses: dominikh/staticcheck-action@v1.2.0
            with:
                version: "2022.1.3"
                working-directory: "./disgolink"
                install-go: false
